WIP Options format: shell, lines, comma
raineorshine/npm-check-updates pull request #1283
Opened 2023-03-21 20:00 UTC by vanodevium

#1282 

@raineorshine I have some problems with TS :(

Anyway, I'm trying. 

Is this correct implementation? Can I continue work with tests and readme?

2023-03-21 21:18 UTC, raineorshine requested changes

2023-03-21 21:18 UTC, raineorshine commented on src/lib/initOptions.ts
> +  }
You can do this logic in the ternary and avoid changing `const` to `let`.

2023-03-22 12:17 UTC, raineorshine commented
`--format unix` is ambiguous in its own way, and I don't want to imply that this feature is platform specific and can't be used by Windows users. `--format lines` describes the output: one update per line, without anything else. The help system can clarify further.

2023-03-22 12:20 UTC, vanodevium commented
OK. I have done my best.

2023-03-22 20:19 UTC, merged

2023-03-22 20:22 UTC, vanodevium commented
Thanx!