Convert to ESM
raineorshine/npm-check-updates pull request #1391
Opened 2024-04-01 16:25 UTC by wmertens

2024-04-01 16:29 UTC, wmertens commented
The failing test is trying to import the esm module as cjs which should't work.

2024-04-01 17:19 UTC, raineorshine commented
The CJS test can be removed since it will no longer be supported.

2024-04-04 10:45 UTC, wmertens commented
All good now 😃

2024-04-04 12:37 UTC, raineorshine requested changes

2024-04-25 15:37 UTC, raineorshine commented
@wmertens Just checking in to see if you have an update.

2024-04-25 15:44 UTC, wmertens commented on test/e2e.sh
> +  set +e
IIRC this was causing the verdaccio shutdown to fail. Not sure any more :-/

2024-04-25 15:46 UTC, wmertens commented on package.json
> +    "test:unit": "vitest test/package-managers/*",
how did I drop it? Not sure why that message though.

2024-04-25 15:49 UTC, raineorshine commented on package.json
> +    "test:unit": "vitest test/package-managers/*",
`mocha test test/package-managers/*` specifies two paths: `./test` and `./test/package-managers/*`. This edit removes the `./test` path from the `test:unit` script (which is the main test suite for the project).

2024-04-25 16:04 UTC, wmertens commented on package.json
> +    "test:unit": "vitest test/package-managers/*",
ah maybe because it always used chdir and vitest uses workers?

2024-04-25 16:15 UTC, raineorshine commented on package.json
> +    "test:unit": "vitest test/package-managers/*",
`process.chdir` is only used in `getAllPackages.test.ts`, and it appears to be a remnant of some local testing that another developer did. The tests pass without it, so I removed it in 688c07f3a7fcda4a879ab3476fb5c70972e7505e.

2024-04-25 16:24 UTC, wmertens commented
I'm trying to rebase but

```
npm ERR! command bash -c node install.js
npm ERR! Failed to find package "@oven/bun-linux-x64". You may have used the "--no-optional" flag when running "npm install".
npm ERR! Failed to find package "@oven/bun-linux-x64-baseline". You may have used the "--no-optional" flag when running "npm install".
```

2024-04-25 18:20 UTC, raineorshine commented
Sorry about that! I got the same thing, but I was hoping it would work once the lock file was updated. It installs fine in ci mode. 

Try `npm install -f bun`. That worked for me. I'll circle back with a better fix soon.

2024-04-25 22:50 UTC, raineorshine commented
Okay. I think since bun is not very cross-platform compatible, I will move it into a separate optional test script, and remove it from devDependencies.

2024-04-26 01:27 UTC, raineorshine commented
Okay, I've completely offloaded the bun tests to a separate script.

2024-09-01 17:31 UTC, raineorshine commented
Blocked on https://github.com/raineorshine/npm-check-updates/pull/1391#discussion_r1551595674

I'm going to close this, as it's probably too far behind to be useful now. Thank you anyway!

2024-09-01 17:31 UTC, closed without merging