Reduce bundle size
raineorshine/npm-check-updates pull request #1397
Opened 2024-04-11 13:44 UTC by SukkaW

The PR follows #1394 and #1396.

The PR does the following things:

- Removes more lodash usage
- Replaces `lodash/cloneDeep` with https://npm.im/rfdc
- Replaces `lodash/isEqual` with https://npm.im/dequal
- Replaces `lodash/pick`, `lodash/pickBy`, and `lodash/sortBy` with self-implemented methods

2024-04-11 14:11 UTC, raineorshine requested changes
Thank you!

2024-04-12 12:25 UTC, SukkaW commented on vite.config.mts.timestamp-1712836068862-1fab47e1f7e58.mjs
> +// vite.config.mts
Oh!

This file is an intermediate file created by vite, it should have been deleted by vite after the build, I must have aborted the process somehow and it leaks to the PR.

2024-04-12 12:26 UTC, SukkaW commented on vite.config.mts.timestamp-1712836068862-1fab47e1f7e58.mjs
> +// vite.config.mts
Removed in [`fd881ba` (#1397)](https://github.com/raineorshine/npm-check-updates/pull/1397/commits/fd881bae7710d071d6df282369465c17e1a5f5cf).

2024-04-12 12:41 UTC, raineorshine approved these changes

2024-04-12 13:33 UTC, merged